name: Node.js CI

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - master
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
      env:
        API_KEY: ${{ secrets.DEVTO_APIKEY }}
    - run: npm install    
    - run: node publish.js
